- name: Ensure user 'student' exists with password
  become_user: postgres
  shell: |
    psql -c "DO \$\$ 
    BEGIN 
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'student') THEN 
            CREATE USER student WITH PASSWORD 'student_pass'; 
        END IF; 
    END 
    \$\$;"

- name: Allow student to connect to all databases
  become_user: postgres
  shell: psql -c "ALTER USER student WITH LOGIN;"

- name: Run SELECT 1 to verify connection
  become_user: postgres
  shell: psql -c "SELECT 1;"
